# This file is normally generated by `nixos-generate-config --root /mnt`.
# Replace this stub with the generated file from your actual server hardware
# before running nixos-install.
#
# See README.md — "First-time installation" — for how to generate this.
{ ... }:
{
  # TODO: replace with the output of:
  #   sudo nixos-generate-config --root /mnt
  #   cp /mnt/etc/nixos/hardware-configuration.nix \
  #      /mnt/etc/nixos/hosts/server/hardware-configuration.nix
}
