# This file is normally generated by `nixos-generate-config --root /mnt`.
# Replace this stub with the generated file from your actual server hardware
# before running nixos-install.
#
# See README.md — "First-time installation" — for how to generate this.
{ ... }:
{
  # TODO: replace with the output of:
  #   sudo nixos-generate-config --root /mnt
  #   cp /mnt/etc/nixos/hardware-configuration.nix \
  #      /mnt/etc/nixos/hosts/server/hardware-configuration.nix

  # Placeholder root filesystem — required by `nix flake check`.
  # nixos-generate-config will produce the real entries for your disk layout.
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  # Recommended: mount a dedicated second disk at /srv for all service data
  # (PDS repository, Mastodon media, and Mastodon secrets).  Keeping service
  # data on a separate disk makes it easy to resize, snapshot, or migrate
  # independently of the OS volume, and reduces the blast radius of a full-
  # disk event on either side.
  #
  # Format the data disk before first boot, then uncomment this block:
  #
  #   sudo mkfs.ext4 -L data /dev/vdb          # adjust device as needed
  #
  # fileSystems."/srv" = {
  #   device  = "/dev/disk/by-label/data";
  #   fsType  = "ext4";
  #   options = [ "defaults" "noatime" ];
  # };

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sd_mod" "sr_mod" ];
}
